# Generated by Django 6.1 on 2026-09-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
